name: reels_demo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  gap: ^3.0.1
  intl: ^0.19.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  get_it: ^8.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  fluttertoast: ^8.2.8
  infinite_scroll_pagination: ^4.0.0
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  readmore: ^3.0.0
  floor: ^1.5.0
  sqflite: ^2.4.0
  flutter_cache_manager: ^3.4.1
  internet_connection_checker_plus: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
